version: '3'
services:

    hackernews:
     build: ./hackernews
     container_name: hackernews_client
     environment:
      - MONGODB_URI=mongodb:27017
     ports:
      - "5000:5000"
     volumes:
      - .:/hackernews_client
     depends_on:
      - mongodb
     links:
      - mongodb

    mongodb:
        image: mongo:3.6.4
        ports:
            - "27017:27017"
